theme: jekyll-theme-tactile
collections:
 synsets:
  output: true
  sort_by: synset
 Germanterms:
  sort_by: synset

defaults:
 - scope:
    path: ""
    type: "synsets"
   values:
    layout: "synset"
